apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: iti-java-container
        image: mahmoudsoudi/iti-java:21
        ports:
        - containerPort: 8090
